# kernel update reboot
reboot_timeout: 600

# proxy
proxy: http://192.168.254.1:1081

# repo dir
repo_dir: /usr/share/nginx/html/x86_64

#
containerd_version: containerd.io-1.6.25
nerdctl_package: nerdctl-1.7.1-linux-amd64.tar.gz
cni_plugin: cni-plugins-linux-amd64-v1.3.0.tgz

