---
- name: all host run this task
  shell: hostname
  register: info

- name: modify hostname
  ansible.builtin.hostname:
    name:  "{{ inventory_hostname  }}"
  when: info.stdout == "localhost.localdomain"


# 注意 ip 就是主机名, ip从ansible hosts中获得
#- name: Get Master IP addresses of group master (1/2)
#  set_fact:
#    hostnames: []

#- name: Print all available facts
#  ansible.builtin.debug:
#    var: ansible_facts

#- name: Gather hostnames
#  set_fact:
#    hostnames: "{{ hostnames | default([]) + [hostvars[item].ansible_facts.fqdn] }}"
#  loop: "{{ groups['all'] }}"

#- name: Print all available facts
#  ansible.builtin.debug:
#    var: hostnames

# 注意 ip 就是主机名, ip从ansible hosts中获得
- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ item }} {{ hostvars[item].ansible_facts.fqdn }}'
    state: present
  with_items: "{{ groups['all'] }}"
