#- hosts: ansible_manager
#  gather_facts: false
#  roles:
#  - {role: pre_download} # ansible 需要能上网

- hosts: master
  roles:
#  - {role: repo}  # kubelet kubeadm 
#  - {role: env_preparation} # chrony sysctl ulimit swap
#  - {role: hostname}
#  - {role: kernel_update}
#  - {role: containerd}  
  - {role: ha_module_install}


- hosts: ansible_manager
  gather_facts: false
  roles:
  - {role: kubeadm_config_create}
  - {role: registry_install}
  - {role: pre_images} #
#

#- hosts: master
#  roles:
#  - {role: master-openports}
#- hosts: master,worker
#  roles:
#  - {role: repo}
  #- {role: repo}
  #- {role: firewalld}
  #- {role: disk}
  #- {role: ipvs}
  #- {role: copy_bins}
#  - {role: proxy-cleanup}
  #- {role: worker-openports}
#  - {role: kubelet-cleanup}
