apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: haproxy
    tier: control-plane
  name: kube-haproxy
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: kube-haproxy
    image: 192.168.254.133:5000/k8simages/haproxy:2.4.24-alpine3.18
    volumeMounts:
    - name: haproxy-cfg
      readOnly: true
      mountPath: /usr/local/etc/haproxy/haproxy.cfg
    resources:
      requests:
        cpu: 2
  volumes:
  - name: haproxy-cfg
    hostPath:
      path: /etc/kubernetes/kube-haproxy.cfg
      type: FileOrCreate
